// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaylorBennett.BackService.Models;

namespace TaylorBennett.BackService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190905010621_RefactorV2")]
    partial class RefactorV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("TaylorBennett.BackService.Models.BlogPost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("BlogPostBody");

                    b.Property<DateTime>("BlogPostDate");

                    b.Property<string>("BlogPostTitle");

                    b.HasKey("ID");

                    b.ToTable("BlogPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
